M48
; DRILL file {KiCad 7.0.2-0} date 2023 December 31, Sunday 00:12:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-31T00:12:22-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.500
%
G90
G05
T1
X128.07Y-140.59
X133.85Y-140.59
T2
X71.571Y-136.95
X71.571Y-174.95
X139.571Y-136.95
X139.571Y-174.95
T0
M30
