M48
; DRILL file {KiCad 8.0.5} date 2026-07-11T20:47:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-11T20:47:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X114.15Y-97.23
X114.15Y-103.01
T2
X113.587Y-86.75
X113.587Y-91.15
M30
