M48
; DRILL file {KiCad (6.0.10-0)} date Tuesday, February 14, 2023 at 10:29:46 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-14T22:29:46-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X265.04Y-61.94
X265.04Y-67.72
T2
X195.52Y-51.25
X195.52Y-83.75
X267.17Y-51.25
X267.17Y-83.75
T0
M30
