M48
; DRILL file {KiCad 7.0.2-0} date 2023 September 20, Wednesday 20:36:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-20T20:36:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.500
%
G90
G05
T1
X135.841Y-159.91
X135.841Y-165.69
T2
X71.571Y-136.95
X71.571Y-174.95
X139.571Y-136.95
X139.571Y-174.95
T0
M30
