M48
; DRILL file {KiCad 7.0.2-0} date 2024 February 25, Sunday 21:14:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-25T21:14:00-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X128.07Y-140.59
X133.85Y-140.59
T2
X71.62Y-136.98
X71.63Y-174.9
X139.54Y-136.95
X139.54Y-174.93
T0
M30
