M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 07, Sunday 22:08:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-07T22:08:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X260.61Y-64.98
X260.61Y-70.76
T2
X212.86Y-76.07
X261.27Y-52.79
T0
M30
