M48
; DRILL file {KiCad (6.0.10-0)} date Monday, April 17, 2023 at 11:13:13 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-17T23:13:13-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X181.3Y-77.4
X181.3Y-126.4
X239.3Y-77.4
X239.3Y-126.4
T0
M30
