M48
; DRILL file {KiCad 8.0.0} date 2024-03-08T16:01:44-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-08T16:01:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0320
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X7.045Y-2.1669
X7.045Y-2.659
X7.135Y-2.1669
X7.135Y-2.659
T2
X7.2547Y-2.0744
X7.9346Y-2.6429
M30
