M48
; DRILL file {KiCad 7.0.2-0} date 2023 April 27, Thursday 21:18:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-27T21:18:19-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X31.09Y-74.06
X31.09Y-79.84
T2
X35.89Y-61.02
X48.04Y-83.7
T0
M30
