M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 18, Thursday 00:20:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-18T00:20:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X260.61Y-64.98
X260.61Y-70.76
T2
X217.03Y-72.1
X261.97Y-51.43
T0
M30
